config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: :omniauth_callbacks}
  root controller: :recipes, action: :index
  resources :recipes, except: [:destroy] do
    collection do
      post :search
    end
    resources :comments
    resources :ratings, only: [:create]
  end
  resources :forks, only: [:create]
  resources :collections, only: [:index, :create, :destroy, :show]
  resources :users, only: [:show]
  mount ActionCable.server => '/cable'
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :recipes
  has_one_attached :pdf
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :authenticate_user!

  def index
    @collection = current_user.collection
  end

  def show
    @collection = current_user.collection
    #@collection.recipes.with_preloaded_image
    begin
      PdfGeneratorService.new(@collection).generate_pdf
      message ='Your Recipe book has been created'
      ActionCable.server.broadcast 'notifications', message: message
      render json: {url: rails_blob_url(@collection.pdf)}, status: :ok
    rescue => e
      message = e.message
      ActionCable.server.broadcast 'notifications', message: message
    end
    
  end

  def create
    current_user.collection.recipes << current_recipe
    current_user.save
    flash[:notice] = "Recipe was added to collection"
    redirect_back fallback_location: root_path
  end

  def destroy
    current_user.collection.recipes.delete(current_recipe)
    current_user.save
    flash[:notice] = "Recipe was removed from collection"
    redirect_back fallback_location: root_path
  end

  private
  def current_recipe
    Recipe.find(params[:id])
  end
end

app/views/collections/index.html.haml
%h1 My Collection
.buttons.flex
  = link_to collection_path(@collection), remote: true, id: 'generate-pdf',  data: { disable_with: "Generating recipe book..." }, class: 'btn' do
    .fas.fa-book
    Create Recipe Book
  = link_to '#', target: '_blank', style: 'display: none;', id: 'view-pdf',  data: { disable_with: "Opening..." }, class: 'btn' do
    .far.fa-file-pdf
    View PDF
.flex.flex-wrap
  - @collection.recipes.each do |recipe|
    .recipe.bg-white.p-4.m-2.rounded.overflow-hidden.shadow-md.max-w-sm
      %h3= link_to recipe.title, recipe_path(recipe)
      %p= recipe.description[0..100] + '...'
      .flex.flex-wrap.text-sm.mt-4
        .mr-2= "Posted by:"
        = mail_to recipe.user.email, "#{recipe.user.full_name}"
      .buttons.flex.justify-center.mt-2
        = link_to collection_path(recipe), method: :delete, class: 'btn' do
          .fas.fa-trash-alt
          Remove


:javascript
  document.addEventListener('turbolinks:load', () => {

    let generateLink = document.getElementById('generate-pdf');
    let viewLink = document.getElementById('view-pdf');
    let isPdfGenerated = #{current_user.collection.pdf.attached?}

    const setVisibilityOfViewPdfLink = url => {
      viewLink.href = url
      viewLink.style.display = '';
    }

    if ( isPdfGenerated === true) {
      setVisibilityOfViewPdfLink("#{rails_blob_url(@collection.pdf, disposition: "attachment") if @collection.pdf.attached?}");
    }

    generateLink.addEventListener('ajax:success', event => {
      setVisibilityOfViewPdfLink(event.detail[0].url);
    })
  })