config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: :omniauth_callbacks}
  root controller: :recipes, action: :index
  resources :recipes, except: [:destroy] do
    collection do
      post :search
    end
    resources :comments
    resources :ratings, only: [:create]
  end
  resources :forks, only: [:create]
  resources :collections, only: [:index, :create, :destroy, :show]
  resources :users, only: [:show]
  mount ActionCable.server => '/cable'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :comments
  belongs_to :user
  has_one_attached :image
  validates :title, presence: true, length: {minimum: 3}
  validates :description, presence: true
  validates :ingredients, presence: true
  validates :directions, presence: true
  belongs_to :user
  has_and_belongs_to_many :collections, uniq: true
  belongs_to :category
  has_many :ratings

  scope :with_preloaded_image, -> { preload(image_attachment: :blob) }

  update_index('recipes') { self }

  after_create :notify

  def notify
    ActionCable.server.broadcast 'notifications',
                                  message: "<p>#{self.title} was created!</p>"
  end

  def rated_by?(resource)
    self.ratings.where(user: resource).any?
  end

  def fork(user)
    forked_recipe = self.dup
    attributes = {user: user,
                  original_recipe_id: self.id,
                  title: 'Forked ' + self.title,
                  forked_recipes_ids: [],
                  collection_id: nil}
    forked_recipe.update_attributes(attributes)

    self.forked_recipes_ids << forked_recipe.id
    self.save
    return forked_recipe
  end

  def forked?
    self.original_recipe_id.present?
  end

  def calc_average_rating
    total = self.ratings.map(&:value).sum
    instances = self.ratings.any? ? self.ratings.count : 1  #to avoid division by zero error
    average = total / instances
    average
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :get_recipe, only: [:show, :edit, :update]
  before_action :authorize_record, only: [:edit, :update]
  before_action :load_categories, except: [:show]

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.image.attach(params[:recipe][:image])
    if @recipe.save
      flash[:notice] = "Recipe Sucessfully created"
      redirect_to root_path
    else
      flash[:alert] = @recipe.errors.full_messages.first
      render 'new'
    end
  end

  def index
  end

  def show
    @original_recipe = Recipe.find(@recipe.original_recipe_id) if @recipe.forked?
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      @recipe.image.attach(params[:recipe][:image])
      flash[:notice] = "You have successfully edit recipe!"
      redirect_to recipe_path(@recipe)
    else
      flash[:alert] = @recipe.errors.full_messages.first
      render :edit
    end
  end

  def search
    RecipesIndex.import
    query = RecipesIndex.query(fuzzy: {title: params[:search]})
    @hits = query.hits.count
    @recipes = query.objects
    render :search
  end

private

 def recipe_params
   recipe = params.require(:recipe).permit(:title, :description, :ingredients, :directions, :category_id )
   recipe[:user] = current_user
   recipe
 end

 def get_recipe
    @recipe = Recipe.find(params[:id])
 end

 def authorize_record
    authorize @recipe
 end

def load_categories
  @categories = Category.all
end

end

app/views/recipes/edit.html.haml
%h2 Edit Recipe


.recipe-new
  = form_with model: @recipe, local: true do |form|

    %h3= form.label :title
    = form.text_field :title

    %h3 Category
    #select.text-xl
      = form.collection_select :category_id, @categories, :id, :name, prompt: 'Please select a Category...', class: 'bg-white'

    %h3= form.label :description
    = form.text_area :description
    %h3= form.label :ingredients
    = form.text_area :ingredients
    %h3= form.label :directions
    = form.text_area :directions

    %h3 Image
    #choose.text-xl
      = form.file_field :image
    .mt-4.text-xl
      = form.submit

app/views/recipes/index.html.haml
%h1.text-center.mb-4 Recipes
- @categories.each do |category|
  %h3.text-center= category.name
  .category.flex.flex-wrap.justify-center
    - category.recipes.each do |recipe|
      .recipe.bg-white.p-4.m-2.rounded.overflow-hidden.shadow-md.min-w-2xs.max-w-xs{id: "recipe-#{recipe.id}"}
        = link_to (image_tag rails_blob_path(recipe.image), class: 'w-full'), recipe_path(recipe) unless recipe.image.attachment.nil?
        .px-4.py-4
          %h3.mb-2= link_to recipe.title, recipe_path(recipe)
          %p.text-grey-darker= recipe.description[0..200] + '...'
          .px-4.py-4
            .flex.flex-wrap.justify-center.text-sm
              .mr-2
                Posted by:
                = mail_to recipe.user.email, "#{recipe.user.full_name}"

app/views/recipes/new.html.haml
%h1 Add New Recipe

.recipe-new
  = form_with model: @recipe, local: true do |form|

    %h3= form.label :title
    = form.text_field :title

    %h3 Category
    #select.text-xl
      = form.collection_select :category_id, @categories, :id, :name, prompt: 'Please select a Category...', class: 'bg-white'

    %h3= form.label :description
    = form.text_area :description, cols: "30", rows: "10"
    %h3= form.label :ingredients
    = form.text_area :ingredients, cols: "30", rows: "10"
    %h3= form.label :directions
    = form.text_area :directions, cols: "30", rows: "10"

    %h3 Image
    .flex.mb-4
      .overflow-hidden.relative.w-64.mt-4.mb-4
        %input#uploader.bg-orange.p-4.rounded.overflow-hidden.shadow-md.min-w-2xs.max-w-xs.mt-4.text-xl.text-white{type: 'button', value: 'Upload image'}
        = form.file_field :image, class: 'cursor-pointer absolute block opacity-0 pin-r pin-t'
      #preview{class: 'w-1/2'} 
   
    .mt-4.text-xl
      = form.submit


:javascript 
  (function() {
    if (typeof Turbolinks === "undefined" || Turbolinks === null) {
      location.reload;
    }

    Turbolinks.dispatch("turbolinks:load");

  }).call(this);
  document.addEventListener('turbolinks:load', () => {
    if (window.File && window.FileList && window.FileReader) {
      let button = document.getElementById('uploader')
      var filesInput = document.getElementById("recipe_image");
      button.addEventListener('click', ()=>{
        filesInput.click();
      })
      filesInput.addEventListener("change", function (event) {
        var files = event.target.files;
        var output = document.getElementById("preview");
        output.innerHTML = ''
        for (var i = 0; i < files.length; i++) {
          var file = files[i];
          if (!file.type.match('image'))
            continue;
          var picReader = new FileReader();
          picReader.addEventListener("load", function (event) {
            var picFile = event.target;
            var div = document.createElement("div");
            div.innerHTML = "<img class='thumbnail' style='height: auto%; width: 500px;' src='" + picFile.result + "'" +
              "title='" + picFile.name + "'/>";
            output.insertBefore(div, null);
          });
          picReader.readAsDataURL(file);
        }
  
      });
    }
  } )
  
  

app/views/recipes/search.html.haml
%h1= "Found #{@hits} recipes"

- @recipes.each do |recipe|
  .recipe.bg-white.p-4.m-2.rounded.overflow-hidden.shadow-md.max-w-sm
    %h3= link_to recipe.title, recipe_path(recipe)
    %p= recipe.description[0..100] + '...'
    .flex.flex-wrap.text-sm.mt-4
      Posted by:
      = mail_to recipe.user.email, recipe.user.full_name

app/views/recipes/show.html.haml
.recipe.max-w-full.bg-white.p-4.my-4.rounded.shadow
  .recipe-upper.flex
    .recipe-left.w-1by2.p-2
      %h1.text-center.text-orange= @recipe.title
      #average-rating
      %br
      %p
        Posted by:
        = mail_to @recipe.user.email, @recipe.user.full_name
      %p
        - if @recipe.forked?
          Forked from:
          = link_to @original_recipe.title , recipe_path(@original_recipe)

      %br
      %h3 Category
      %p= @recipe.category.name
      %h3 Description
      %p= @recipe.description

    .recipe-right.w-1by2.p-2
      .recipe-buttons.flex.items-start.justify-end.mb-4
        -if user_signed_in? && policy(@recipe).edit?
          = link_to edit_recipe_path, class: 'btn' do
            .fas.fa-edit
            Edit Recipe

        -if user_signed_in?
          = link_to forks_path(id: @recipe.id), method: :post , class: 'btn' do
            #fork-button.flex
              .fas.fa-code-branch
              Fork
              - if @recipe.forked_recipes_ids.any?
                .text-brown.bold.ml-2.pl-2.border-l-2.border-orange
                  = @recipe.forked_recipes_ids.count

          - if current_user.collection.recipes.include?(@recipe)
            .disabled-btn= "In Collection"
          - else
            = link_to collections_path(id:@recipe.id), method: :post, class: 'btn' do
              .fas.fa-plus
              Add to Collection

      .self-end
        = image_tag rails_blob_path(@recipe.image), class: 'w-100%' unless @recipe.image.attachment.nil?

  .recipe-down.p-2
    .recipe-text.border-b.pb-2.mb-2
      %h3 Ingredients
      %p= @recipe.ingredients
      %h3 Directions
      %p= @recipe.directions

    .rating-div.border-b.pb-2.mb-2
      - unless @recipe.rated_by?(current_user)
        %h3
          Rate:
          %span#rating
            - 5.times.reverse_each do |i|
              = content_tag(:span, "&#9734".html_safe, data: {rating: "#{i + 1}"}, id: "star-#{i + 1}", class: 'star')

    .comments-div
      - count = @recipe.comments.count
      - if  count == 1
        .flex
          %h3.mr-2= "1 Comment"
          %i.far.fa-comment-dots.mt-3
      - elsif count > 1
        .flex
          %h3.mr-2= "#{count} Comments"
          %i.far.fa-comment-dots.mt-3

      - @recipe.comments.each do |comment|
        .bg-white.p-4.m-2.rounded.overflow-hidden.shadow-md.w-1by2
          %p= comment.body
          .flex.justify-end.text-sm
            .mr-2
              Commented by:
              = mail_to comment.user.email, "#{comment.user.full_name}"

    .comments-form
      - if user_signed_in?
        = form_with(model: [ @recipe, @recipe.comments.build ], local: true) do |form|
          .flex.items-end
            .w-1by2.mr-4.ml-2.-mb-3
              = form.text_area :body, placeholder: "Comment here"
            = form.submit 'Comment', class: 'btn'

:javascript
    const showRatingFunction = (rating, message) => {
      let dispalyRatingElement = document.getElementById('average-rating')
      if (rating == 0) {
        dispalyRatingElement.style.display = 'none';
        return false;
      } else {
        dispalyRatingElement.innerHTML = ''
        dispalyRatingElement.style.display = '';
      }

      // We want to display 5 stars in total
      let label = document.createElement('span')
      label.innerText = "Average Rating:"
      dispalyRatingElement.appendChild(label)
      // Display black stars based on the current rating
      rating.times( () => {
        let content = document.createElement('span')
        content.innerHTML = "&#9733"
        dispalyRatingElement.appendChild(content)
      } );
      // Display white star based on 5 - current rating
      let whiteStarCount = 5 - rating
      whiteStarCount.times( () => {
        let content = document.createElement('span')
        content.innerHTML = "&#9734"
        dispalyRatingElement.appendChild(content)
      } );

      let usersMessage = document.createElement('span')

      usersMessage.innerText = message
      dispalyRatingElement.appendChild(usersMessage)

      return false;
    }

    document.addEventListener('turbolinks:load', () => {
      let averageRating = #{@recipe.calc_average_rating}
      let averageRatingMessage = " By #{@recipe.ratings.count} #{'user'.pluralize(@recipe.ratings.count)}."
      let ratingStars = document.querySelectorAll('span .star')
      let noticeDiv = document.querySelector('.notice')
      let alertDiv = document.querySelector('.alert')
      let ratingDiv = document.querySelector('#rating')

      showRatingFunction(averageRating, averageRatingMessage)

      ratingStars.forEach((star)=>{
        star.addEventListener('click',(event)=>{
          event.preventDefault()
          let value = star.dataset.rating
          let body = JSON.stringify({rating: value })
          fetch("#{recipe_ratings_path(@recipe)}", {
            method: 'POST',
            body: body,
            credentials: 'include',
            headers: {
              'Content-Type': 'application/json',
              'X-Requested-With': 'XMLHttpRequest',
              'X-CSRF-Token': Rails.csrfToken()
          }}).then(function(response) {
            return response.json();
          }).then(function(data) {
            noticeDiv.innerHTML = data.message
            let displayMessage = data.display_message
            let averageRating = data.average_rating
            showRatingFunction(averageRating, displayMessage)
            ratingDiv.style.display = 'none'
            console.log(data)
          }).catch((error) => {
            alertDiv.innerHTML = error
            console.log(error)
          });
        })
      })
    })