config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: :omniauth_callbacks}
  root controller: :recipes, action: :index
  resources :recipes, except: [:destroy] do
    collection do
      post :search
    end
    resources :comments
    resources :ratings, only: [:create]
  end
  resources :forks, only: [:create]
  resources :collections, only: [:index, :create, :destroy, :show]
  resources :users, only: [:show]
  mount ActionCable.server => '/cable'
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :admin]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]

  validates :full_name, presence: true

  has_many :recipes
  has_one :collection
  has_many :comments

  after_create :make_collection

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.full_name = auth.info.name
      user.password = Devise.friendly_token[0,20]
      #user.image = auth.info.image # assuming the user model has an image
    end
  end

  def make_collection
    Collection.create(user: self)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @original_recipes = current_user.recipes.where(original_recipe_id: nil)
    @forked_recipes = current_user.recipes.where.not(original_recipe_id: nil)
  end
end

app/views/users/show.html.haml
%h1 My Profile
%br
%o
  Name: 
  %span
    = current_user.full_name
%p
  Email:
  %span
    = mail_to current_user.email
%br

#my-original-recipes
  %h1 My Original Recipes
  %br
  .category.flex.flex-wrap
    - @original_recipes.each do |recipe|
      .recipes.bg-white.p-4.m-2.rounded.overflow-hidden.shadow-md.max-w-sm{id: "recipe-#{recipe.id}"}
        %h3= link_to recipe.title, recipe_path(recipe)
        %p= recipe.description[0..100] + '...'

        .buttons.flex.mt-2.justify-center.items-end
          = link_to edit_recipe_path(recipe), class: 'btn' do
            .fas.fa-edit
            Edit Recipe
          = link_to forks_path(id: recipe.id), method: :post, class: 'btn' do
            .fas.fa-code-branch
            Fork
          - if current_user.collection.recipes.include?(recipe)
            .disabled-btn= "In Collection"
          - else
            = link_to collections_path(id:recipe.id), method: :post, class: 'btn' do
              .fas.fa-plus
              Add to Collection


#my-forked-recipes
  %h1 My Forked Recipes
  %br
  .category.flex.flex-wrap
    - @forked_recipes.each do |recipe|
      .recipes.bg-white.p-4.m-2.rounded.overflow-hidden.shadow-md.max-w-sm{id: "recipe-#{recipe.id}"}
        %h3= link_to recipe.title, recipe_path(recipe)
        %p= recipe.description[0..100] + '...'

        .buttons.flex.mt-2.justify-center.items-end
          = link_to edit_recipe_path(recipe), class: 'btn' do
            .fas.fa-edit
            Edit Recipe
          = link_to forks_path(id: recipe.id), method: :post, class: 'btn' do
            .fas.fa-code-branch
            Fork
          - if current_user.collection.recipes.include?(recipe)
            .disabled-btn= "In Collection"
          - else
            = link_to collections_path(id:recipe.id), method: :post, class: 'btn' do
              .fas.fa-plus
              Add to Collection