config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: :omniauth_callbacks}
  root controller: :recipes, action: :index
  resources :recipes, except: [:destroy] do
    collection do
      post :search
    end
    resources :comments
    resources :ratings, only: [:create]
  end
  resources :forks, only: [:create]
  resources :collections, only: [:index, :create, :destroy, :show]
  resources :users, only: [:show]
  mount ActionCable.server => '/cable'
end

app/views/layouts/_navbar.html.haml
.navbar.bg-white.border-b.font-semibold
  .container.mx-auto.px-2
    .flex.justify-between.border-b
      #logo.flex.items-center
        = link_to image_tag('foodhub-logo.png', class: 'w-48 mr-4'), root_path

      #login-menu.flex.items-center
        - if user_signed_in?
          .py-4.mr-4.text-grey= "Logged in as: #{current_user.full_name}"
          = link_to 'Sign Out', destroy_user_session_path,
                                method: :delete,
                                class: 'menu-item'
        - else
          = link_to 'Sign Up', new_user_registration_path, class: 'menu-item'
          = link_to 'Login', new_user_session_path, class: 'menu-item'
          = link_to 'Login with Facebook', user_facebook_omniauth_authorize_path, class: 'menu-item'

    .flex.justify-between
      #main-menu.flex.justify-start.items-center
        = link_to "Home", root_path, class: 'menu-item'
        - if user_signed_in?
          = link_to "My Collection", collections_path, class: 'menu-item'
          = link_to "My Profile", user_path(current_user), class: 'menu-item'
          = link_to 'New Recipe', new_recipe_path, class: 'btn'

      #search
        = form_with url: search_recipes_path, method: :post, local: true, class: 'flex' do |form|
          = form.text_field :search, placeholder: 'Search for Recipes...', type: 'search'
          = form.submit raw("&#x1F50E;"), id: 'search-mag'

app/views/layouts/application.html.haml
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title FoodHub
    %link{crossorigin: "anonymous", href: "https://use.fontawesome.com/releases/v5.1.0/css/all.css", integrity: "sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt", rel: "stylesheet"}
    = csrf_meta_tags
    = csp_meta_tag
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    = stylesheet_pack_tag 'application'
  %body
    = render "layouts/navbar"
    .container.mx-auto
      #notifications.flex.bg-orange-lighter.border-t-4.border-orange.rounded-b.shadow.items-center.px-4
        #flashes
          .notice= notice
          .alert= alert
    .container.mx-auto
      = yield